### ISSUE TITLE
Work on community development

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/DECARCERATION-PLATFORM#21]
We need a good plan to make sure developers are participating and planning against the backlog. 

Some ideas:

1. Create development roadmap. (visual would be helpful)
2. Have incentives tied to releases
3. Establish coding times (Code and Brews, Hack-n-tell, etc)
4. Utilize CfM Hack nights for recruitments business and demos
5. Clearly outline needs list

We would love to hear any ideas and thoughts that you have.

**Comment by romkedehaan** [comment]
@paul-rinaldi to list out what events we will be at coding.

**Comment by kaftand** [comment]
First off, I think this is a great issue and maybe we can reach out to other CFA Chapters for additional input. 

I have faced a few challenges in contributing, and I think they could be mitigated with more frequent "team wide" check-ins.

Some examples:
- An issue I worked on was later deemed unimportant. If I spent a week working on it instead of a month, I could have spent more time on more important backlog items.
- I have worked on issues between CFM meetings and found I was doing something wrong / doing the wrong thing. More frequent checkins could have kept me from going too far in the wrong direction.
- Sometimes I didn't really know what I should be working on. Paul has been helpful and gave me his cell number, but that might not be a solution that scales.
- Sometimes, I feel like I should be working on something, but without a deadline on the horizon, I won't prioritize over the other stuff (with deadlines) I got going on.

I am enjoying working on this project, and I very much appreciate the work Paul and Romke put in. I'm excited to keep pushing and turn a corner on productivity!

**Comment by paul-rinaldi** [comment]
I did some research and created a doc that can encapsulate the todos for building our community!
https://docs.google.com/document/d/10czaJSt3MOHezhz6eXg5FNE2lRkh1aTxPYsqP1QZ9aU/edit?usp=sharing

**Comment by Aycrazy** [comment]
I'm divulging something slightly early, but if you meet somewhere and make it a meeting over a meal we will reimburse you for the cost of the food. We are still working out the standard operating procedure for how we will get requests for reimbursement, but it will probably be something like, tell us a week ahead of time, how many ppl, and what the expected cost is...

**Comment by paul-rinaldi** [comment]
Having a solid foundation I think is key in the beginning so that when we complete the MVP roadmap, we can iterate off that or take bits and pieces from that and create the final webapp solution. Then additons and fixes are easier to complete. Additionally, having a core team of paid devs may help promote better traction?

**Comment by kaftand** [comment]
> Having a solid foundation I think is key in the beginning so that when we complete the MVP roadmap, we can iterate off that or take bits and pieces from that and create the final webapp solution. 

I highly agree with you here Paul

**Comment by paul-rinaldi** [comment]
Through advertising in Facebook Groups and slack channels, recruitment has increased. There's a ton of awesome people who want to make an impact. Still unsure on best practices for retainment but I'm less convinced that it's super vital... in the short term at least.

After talking with the creators of [https://streetlives.nyc](https://streetlives.nyc), I learned that:
1) developers come and go
2) human-centered design teams do well with these typical [roles](https://docs.google.com/spreadsheets/d/1e6Ccg4dUUp9vX4w6uRpwWVhu6EdH-CYmU7RXQU15Rbg/edit?usp=sharing) but don't always consist of all of them or them being paid
3) pairing a Sr. Engineer with a Jr. Engineer like myself can allow for flexibility if Sr. Engineers don't have the time consistently but junior engineers need help with architecting and larger design choices. This may apply to other roles.
4) use what you can from other projects, open-sourced data sets, and query standards

so I will be closing this issue but continually documenting what is working and what's not in this project. I will continue to interview open source developers and founders on what's worked.
